### ISSUE TITLE
LogonProviderType is assigned based on LogOnType parameter

### ISSUE THREAD

**Issue by TJEvans** [jaredcatkinson/PSReflect-Functions#15]
https://github.com/jaredcatkinson/PSReflect-Functions/blob/0c7b2bd1f424883e4c2cc65fe3c50372e8a0786d/advapi32/LogonUser.ps1#L101  I believe you intended to switch on the $LogonProvider field at the referenced line

**Comment by vors** [comment]
Good catch! Care to send a pull request?

**Comment by vors** [comment]
Nice! This issue didn't get auto-closed for some reason @jaredcatkinson

**Comment by jaredcatkinson** [comment]
Thanks for the heads up @vors
